<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yipeng Liu">

<title>Problem Set 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Problem Set 4_files/libs/clipboard/clipboard.min.js"></script>
<script src="Problem Set 4_files/libs/quarto-html/quarto.js"></script>
<script src="Problem Set 4_files/libs/quarto-html/popper.min.js"></script>
<script src="Problem Set 4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Problem Set 4_files/libs/quarto-html/anchor.min.js"></script>
<link href="Problem Set 4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Problem Set 4_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Problem Set 4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Problem Set 4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Problem Set 4_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Problem Set 4</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yipeng Liu </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="homework-4" class="level1">
<h1>Homework 4</h1>
<p>GitHub Page: https://github.com/EfraimLYP/stats506</p>
<section id="problem-1" class="level2">
<h2 class="anchored" data-anchor-id="problem-1">Problem 1</h2>
<section id="step-1" class="level3">
<h3 class="anchored" data-anchor-id="step-1">Step 1</h3>
<p>Generate a table (which can just be a nicely printed tibble) reporting the mean and median departure delay per airport. Additionally, • Order both tables in descending mean delay. • Both tables should use the airport names not the airport codes. • Both tables should print all rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nycflights13)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Check what the data sets "flights" and "airports" look like</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(flights)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(airports)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(flights, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 19
   year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
  &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
1  2013     1     1      517            515         2      830            819
2  2013     1     1      533            529         4      850            830
3  2013     1     1      542            540         2      923            850
4  2013     1     1      544            545        -1     1004           1022
5  2013     1     1      554            600        -6      812            837
# ℹ 11 more variables: arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;,
#   tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;,
#   hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airports, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 8
  faa   name                            lat   lon   alt    tz dst   tzone       
  &lt;chr&gt; &lt;chr&gt;                         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;       
1 04G   Lansdowne Airport              41.1 -80.6  1044    -5 A     America/New…
2 06A   Moton Field Municipal Airport  32.5 -85.7   264    -6 A     America/Chi…
3 06C   Schaumburg Regional            42.0 -88.1   801    -6 A     America/Chi…
4 06N   Randall Airport                41.4 -74.4   523    -5 A     America/New…
5 09J   Jekyll Island Airport          31.1 -81.4    11    -5 A     America/New…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the airport codes to airport names</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>airports <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(faa, name) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">origin =</span> faa) <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(flights, <span class="at">by =</span> <span class="st">"origin"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, dep_delay) <span class="ot">-&gt;</span> renamed_flights_dep</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the table</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>renamed_flights_dep <span class="sc">%&gt;%</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_dep_delay =</span> <span class="fu">mean</span>(dep_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_dep_delay =</span> <span class="fu">median</span>(dep_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span>mean_dep_delay) <span class="ot">-&gt;</span> flights_1</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the table</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>flights_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  name                mean_dep_delay median_dep_delay
  &lt;chr&gt;                        &lt;dbl&gt;            &lt;dbl&gt;
1 Newark Liberty Intl           15.1               -1
2 John F Kennedy Intl           12.1               -1
3 La Guardia                    10.3               -3</code></pre>
</div>
</div>
<p>Generate a second table (which again can be a nicely printed tibble) reporting the mean and median arrival delay per airport. Exclude any destination with under 10 flights. Additionally, • Order both tables in descending mean delay. • Both tables should use the airport names not the airport codes. • Both tables should print all rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude any destination with under 10 flights</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dest) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">num_flights =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(num_flights <span class="sc">&gt;=</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(flights, <span class="at">by =</span> <span class="st">"dest"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dep_delay, origin, arr_delay, dest) <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="ot">-&gt;</span> filtered_flights</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the airport codes to airport names</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>airports <span class="sc">%&gt;%</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(faa, name) <span class="sc">%&gt;%</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">dest =</span> faa) <span class="sc">%&gt;%</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(filtered_flights, <span class="at">by =</span> <span class="st">"dest"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, arr_delay) <span class="ot">-&gt;</span> renamed_flights_dest</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the table</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>renamed_flights_dest <span class="sc">%&gt;%</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_arr_delay =</span> <span class="fu">mean</span>(arr_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_arr_delay =</span> <span class="fu">median</span>(arr_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span>mean_arr_delay) <span class="ot">-&gt;</span> flights_2</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the table</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(flights_2, <span class="at">n =</span> <span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 99 × 3
   name                                   mean_arr_delay median_arr_delay
   &lt;chr&gt;                                           &lt;dbl&gt;            &lt;dbl&gt;
 1 "Columbia Metropolitan"                       41.8                28  
 2 "Tulsa Intl"                                  33.7                14  
 3 "Will Rogers World"                           30.6                16  
 4 "Jackson Hole Airport"                        28.1                15  
 5 "Mc Ghee Tyson"                               24.1                 2  
 6 "Dane Co Rgnl Truax Fld"                      20.2                 1  
 7 "Richmond Intl"                               20.1                 1  
 8 "Akron Canton Regional Airport"               19.7                 3  
 9 "Des Moines Intl"                             19.0                 0  
10 "Gerald R Ford Intl"                          18.2                 1  
11 "Birmingham Intl"                             16.9                -2  
12 "Theodore Francis Green State"                16.2                 1  
13 "Greenville-Spartanburg International"        15.9                -0.5
14 "Cincinnati Northern Kentucky Intl"           15.4                -3  
15 "Savannah Hilton Head Intl"                   15.1                -1  
16 "Manchester Regional Airport"                 14.8                -3  
17 "Eppley Afld"                                 14.7                -2  
18 "Yeager"                                      14.7                -1.5
19 "Kansas City Intl"                            14.5                 0  
20 "Albany Intl"                                 14.4                -4  
21 "General Mitchell Intl"                       14.2                 0  
22 "Piedmont Triad"                              14.1                -2  
23 "Washington Dulles Intl"                      13.9                -3  
24 "Cherry Capital Airport"                      13.0               -10  
25 "James M Cox Dayton Intl"                     12.7                -3  
26 "Louisville International Airport"            12.7                -2  
27 "Chicago Midway Intl"                         12.4                -1  
28 "Sacramento Intl"                             12.1                 4  
29 "Jacksonville Intl"                           11.8                -2  
30 "Nashville Intl"                              11.8                -2  
31 "Portland Intl Jetport"                       11.7                -4  
32 "Greater Rochester Intl"                      11.6                -5  
33 "Hartsfield Jackson Atlanta Intl"             11.3                -1  
34 "Lambert St Louis Intl"                       11.1                -3  
35 "Norfolk Intl"                                10.9                -4  
36 "Baltimore Washington Intl"                   10.7                -5  
37 "Memphis Intl"                                10.6                -2.5
38 "Port Columbus Intl"                          10.6                -3  
39 "Charleston Afb Intl"                         10.6                -4  
40 "Philadelphia Intl"                           10.1                -3  
41 "Raleigh Durham Intl"                         10.1                -3  
42 "Indianapolis Intl"                            9.94               -3  
43 "Charlottesville-Albemarle"                    9.5                -5  
44 "Cleveland Hopkins Intl"                       9.18               -5  
45 "Ronald Reagan Washington Natl"                9.07               -2  
46 "Burlington Intl"                              8.95               -4  
47 "Buffalo Niagara Intl"                         8.95               -5  
48 "Syracuse Hancock Intl"                        8.90               -5  
49 "Denver Intl"                                  8.61               -2  
50 "Palm Beach Intl"                              8.56               -3  
51 "Bob Hope"                                     8.18               -3  
52 "Fort Lauderdale Hollywood Intl"               8.08               -3  
53 "Bangor Intl"                                  8.03               -9  
54 "Asheville Regional Airport"                   8.00               -1  
55 "Pittsburgh Intl"                              7.68               -5  
56 "Gallatin Field"                               7.6                -2  
57 "NW Arkansas Regional"                         7.47               -2  
58 "Tampa Intl"                                   7.41               -4  
59 "Charlotte Douglas Intl"                       7.36               -3  
60 "Minneapolis St Paul Intl"                     7.27               -5  
61 "William P Hobby"                              7.18               -4  
62 "Bradley Intl"                                 7.05              -10  
63 "San Antonio Intl"                             6.95               -9  
64 "South Bend Rgnl"                              6.5                -3.5
65 "Louis Armstrong New Orleans Intl"             6.49               -6  
66 "Key West Intl"                                6.35                7  
67 "Eagle Co Rgnl"                                6.30               -4  
68 "Austin Bergstrom Intl"                        6.02               -5  
69 "Chicago Ohare Intl"                           5.88               -8  
70 "Orlando Intl"                                 5.45               -5  
71 "Detroit Metro Wayne Co"                       5.43               -7  
72 "Portland Intl"                                5.14               -5  
73 "Nantucket Mem"                                4.85               -3  
74 "Wilmington Intl"                              4.64               -7  
75 "Myrtle Beach Intl"                            4.60              -13  
76 "Albuquerque International Sunport"            4.38               -5.5
77 "George Bush Intercontinental"                 4.24               -5  
78 "Norman Y Mineta San Jose Intl"                3.45               -7  
79 "Southwest Florida Intl"                       3.24               -5  
80 "San Diego Intl"                               3.14               -5  
81 "Sarasota Bradenton Intl"                      3.08               -5  
82 "Metropolitan Oakland Intl"                    3.08               -9  
83  &lt;NA&gt;                                          3.01               -5  
84 "General Edward Lawrence Logan Intl"           2.91               -9  
85 "San Francisco Intl"                           2.67               -8  
86 "Yampa Valley"                                 2.14                2  
87 "Phoenix Sky Harbor Intl"                      2.10               -6  
88 "Montrose Regional Airport"                    1.79              -10.5
89 "Los Angeles Intl"                             0.547              -7  
90 "Dallas Fort Worth Intl"                       0.322              -9  
91 "Miami Intl"                                   0.299              -9  
92 "Mc Carran Intl"                               0.258              -8  
93 "Salt Lake City Intl"                          0.176              -8  
94 "Long Beach"                                  -0.0620            -10  
95 "Martha\\\\'s Vineyard"                       -0.286             -11  
96 "Seattle Tacoma Intl"                         -1.10              -11  
97 "Honolulu Intl"                               -1.37               -7  
98 "John Wayne Arpt Orange Co"                   -7.87              -11  
99 "Palm Springs Intl"                          -12.7               -13.5</code></pre>
</div>
</div>
</section>
<section id="step-2" class="level3">
<h3 class="anchored" data-anchor-id="step-2">Step 2</h3>
<p>How many flights did the aircraft model with the fastest average speed take? Produce a tibble with 1 row, and entires for the model, average speed (in MPH) and number of flights.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check what the data set "planes" looks like</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(planes)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(planes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  tailnum  year type               manufacturer model engines seats speed engine
  &lt;chr&gt;   &lt;int&gt; &lt;chr&gt;              &lt;chr&gt;        &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; 
1 N10156   2004 Fixed wing multi … EMBRAER      EMB-…       2    55    NA Turbo…
2 N102UW   1998 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…
3 N103US   1999 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…
4 N104UW   1999 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…
5 N10575   2002 Fixed wing multi … EMBRAER      EMB-…       2    55    NA Turbo…
6 N105UW   1999 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate each flight's average speed (in MPH)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(tailnum, air_time, distance) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(air_time)) <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">air_time_h =</span> air_time<span class="sc">/</span><span class="dv">60</span>, </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">speed_mph =</span> distance<span class="sc">/</span>air_time_h) <span class="ot">-&gt;</span> flights_speed</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the data frame "planes" and "flights_speed"</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>flights_speed <span class="sc">%&gt;%</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(planes, <span class="at">by =</span> <span class="st">"tailnum"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(tailnum, speed_mph, model)<span class="ot">-&gt;</span> flights_and_planes</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the model with the highest average speed</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>flights_and_planes <span class="sc">%&gt;%</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(model) <span class="sc">%&gt;%</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_speed_by_mod =</span> <span class="fu">mean</span>(speed_mph)) <span class="sc">%&gt;%</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mean_speed_by_mod <span class="sc">==</span> <span class="fu">max</span>(mean_speed_by_mod)) <span class="sc">%&gt;%</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="ot">-&gt;</span> max_model</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the flights that are took by the model with the highest average speed</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>flights_and_planes <span class="sc">%&gt;%</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(model <span class="sc">==</span> max_model<span class="sc">$</span>model[<span class="dv">1</span>]) <span class="ot">-&gt;</span> flights_max_model</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce the result tibble</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>flights_max_model <span class="sc">%&gt;%</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">model =</span> max_model<span class="sc">$</span>model[<span class="dv">1</span>], </span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_speed =</span> max_model<span class="sc">$</span>mean_speed_by_mod[<span class="dv">1</span>], </span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">flights_num =</span> <span class="fu">n</span>()</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> max_model_flights_num</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the tibble</span></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>max_model_flights_num</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  model   avg_speed flights_num
  &lt;chr&gt;       &lt;dbl&gt;       &lt;int&gt;
1 777-222      483.           4</code></pre>
</div>
</div>
</section>
</section>
<section id="problem-2" class="level2">
<h2 class="anchored" data-anchor-id="problem-2">Problem 2</h2>
<p>Load the Chicago NNMAPS data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>nnmaps <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/Users/yipengliu/Desktop/Graduate Courses/STATS 506/Homework/Problem Set 4/chicago-nmmaps.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nnmaps, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  city       date death temp dewpoint     pm10        o3 time season year
1 chic 1997-01-01   137 36.0    37.50 13.05227  5.659256 3654 Winter 1997
2 chic 1997-01-02   123 45.0    47.25 41.94860  5.525417 3655 Winter 1997
3 chic 1997-01-03   127 40.0    38.00 27.04175  6.288548 3656 Winter 1997
4 chic 1997-01-04   146 51.5    45.50 25.07257  7.537758 3657 Winter 1997
5 chic 1997-01-05   102 27.0    11.25 15.34312 20.760798 3658 Winter 1997</code></pre>
</div>
</div>
<p>Write a function get_temp() that allows a user to request the average temperature for a given month.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' This function allows a user to request the average temperature for a given month</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param month month, either a numeric 1-12 or a string</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param year a numeric year</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param data the data set to obtain data from</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param celsius logically indicating whether the results should be in Celsius; default FALSE</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param average_fn a function with which to compute the mean; default is mean</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return a numeric vector of length 1</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>get_temp <span class="ot">&lt;-</span> <span class="cf">function</span>(month, year, data, <span class="at">celsius =</span> <span class="cn">FALSE</span>, <span class="at">average_fn =</span> mean) {</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a new column to store the months</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span> </span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">year_num =</span> year) <span class="sc">%&gt;%</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">month_num =</span> <span class="fu">as.integer</span>(<span class="fu">substring</span>(date, <span class="dv">6</span>, <span class="dv">7</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">month_name =</span> <span class="fu">month</span>(month_num, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>), </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">month_abbr =</span> <span class="fu">month</span>(month_num, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">temp_f =</span> temp<span class="sc">*</span><span class="dv">9</span><span class="sc">/</span><span class="dv">5</span><span class="sc">+</span><span class="dv">32</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(temp, temp_f, month_num, month_name, month_abbr, year_num) <span class="sc">%&gt;%</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(year_num, month_num) <span class="sc">%&gt;%</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">avg_temp_t =</span> <span class="fu">average_fn</span>(temp), </span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>              <span class="at">avg_temp_f =</span> <span class="fu">average_fn</span>(temp_f),</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>              <span class="at">month_num =</span> month_num, </span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>              <span class="at">month_name =</span> month_name, </span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>              <span class="at">month_abbr =</span> month_abbr,</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>              <span class="at">year_num =</span> year_num) <span class="sc">%&gt;%</span></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">distinct</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(month_num <span class="sc">==</span> month <span class="sc">|</span> month_name <span class="sc">==</span> month <span class="sc">|</span> month_abbr <span class="sc">==</span> month, year_num <span class="sc">==</span> year) <span class="ot">-&gt;</span> avg_temp</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Return the result</span></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (celsius) {</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span> (avg_temp<span class="sc">$</span>avg_temp_t)</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span> {</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span> (avg_temp<span class="sc">$</span>avg_temp_f)</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, use the following test cases to test the function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_temp</span>(<span class="st">"Apr"</span>, <span class="dv">1999</span>, <span class="at">data =</span> nnmaps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'year_num', 'month_num'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 121.64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_temp</span>(<span class="st">"Apr"</span>, <span class="dv">1999</span>, <span class="at">data =</span> nnmaps, <span class="at">celsius =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'year_num', 'month_num'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_temp</span>(<span class="dv">10</span>, <span class="dv">1998</span>, <span class="at">data =</span> nnmaps, <span class="at">average_fn =</span> median)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'year_num', 'month_num'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_temp</span>(<span class="dv">13</span>, <span class="dv">1998</span>, <span class="at">data =</span> nnmaps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'year_num', 'month_num'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>numeric(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_temp</span>(<span class="dv">2</span>, <span class="dv">2005</span>, <span class="at">data =</span> nnmaps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'year_num', 'month_num'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>numeric(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_temp</span>(<span class="st">"November"</span>, <span class="dv">1999</span>, <span class="at">data =</span>nnmaps, <span class="at">celsius =</span> <span class="cn">TRUE</span>, <span class="at">average_fn =</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>           <span class="cf">function</span>(x) { </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>             x <span class="sc">%&gt;%</span> sort <span class="ot">-&gt;</span> x </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>             x[<span class="dv">2</span><span class="sc">:</span>(<span class="fu">length</span>(x) <span class="sc">-</span> <span class="dv">1</span>)] <span class="sc">%&gt;%</span> mean <span class="sc">%&gt;%</span> return</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'year_num', 'month_num'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 45.14286</code></pre>
</div>
</div>
<p>As we can see, the 4th and 5th cases return the value numeric(0), which is an incorrect result due to the fact that there is no month 13 and the nnmaps data set does not contain data for 2005.</p>
</section>
<section id="problem-3" class="level2">
<h2 class="anchored" data-anchor-id="problem-3">Problem 3</h2>
<p>First, load or import the data into SAS.</p>
<pre class="sas"><code>/* Generated Code (IMPORT) */
/* Source File: recs2020_public_v5.csv */
/* Source Path: /home/u63636985/sasuser.v94 */
/* Code generated on: 10/17/23, 11:13 PM */

%web_drop_table(WORK.IMPORT);


FILENAME REFFILE '/home/u63636985/sasuser.v94/recs2020_public_v5.csv';

PROC IMPORT DATAFILE=REFFILE
    DBMS=CSV
    OUT=WORK.IMPORT;
    GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.IMPORT; RUN;


%web_open_table(WORK.IMPORT);</code></pre>
<section id="step-1-1" class="level3">
<h3 class="anchored" data-anchor-id="step-1-1">Step 1</h3>
<p>First, we calculate the total number of records for each state, taking into account sampling weights.</p>
<pre class="sas"><code>PROC SUMMARY DATA = WORK.IMPORT NWAY;
    VAR NWEIGHT;
    CLASS state_postal;
    OUTPUT OUT = state_sum SUM = weighted_state_sum;
RUN;</code></pre>
<p>Then, we calculate the sum of the total number of all state records, and the result is 123529025.</p>
<pre class="sas"><code>PROC MEANS DATA = state_sum SUM;
  VAR weighted_state_sum;
RUN;</code></pre>
<p>Next, we calculated the percentage of the total number of records in each state and sort them. We can know from the output that California has the highest percentage of records</p>
<pre class="sas"><code>DATA state_pct;
    SET state_sum;
    total_state_sum = SUM(weighted_state_sum);
    weighted_state_pct = weighted_state_sum/123529025;
    FORMAT weighted_state_pct percent9.2;
RUN;

PROC SORT DATA = state_pct OUT = sorted_state_pct;
  BY DESCENDING weighted_state_pct;
RUN;</code></pre>
<p>Finally, we calculate what percentage of all records correspond to Michigan, which is 3.17% from the output.</p>
<pre class="sas"><code>DATA MI_pct;
    SET sorted_state_pct;
    WHERE state_postal = 'MI';
RUN;</code></pre>
</section>
<section id="step-2-1" class="level3">
<h3 class="anchored" data-anchor-id="step-2-1">Step 2</h3>
<p>In this part, we generate a histogram of the total electricity cost in dollars, amongst those with a strictly positive cost.</p>
<p>First, we filter out values in the data set where DOLLAREL is less than 0.</p>
<pre class="sas"><code>DATA FILTERED_WORK;
  SET WORK.IMPORT;
  if DOLLAREL &gt; 0;
run;</code></pre>
<p>Then, we generate the histogram.</p>
<pre class="sas"><code>PROC UNIVARIATE DATA = FILTERED_WORK;
    VAR DOLLAREL;
    HISTOGRAM;
RUN;</code></pre>
<p>Output:</p>
<pre><code>The UNIVARIATE Procedure

Variable: DOLLAREL

Moments
N   18481   Sum Weights 18481
Mean    1426.06646  Sum Observations    26355134.3
Std Deviation   861.277417  Variance    741798.79
Skewness    2.13904168  Kurtosis    13.1508069
Uncorrected SS  5.12926E10  Corrected SS    1.37084E10
Coeff Variation 60.3953209  Std Error Mean  6.33549171
Basic Statistical Measures
Location    Variability
Mean    1426.066    Std Deviation   861.27742
Median  1258.600    Variance    741799
Mode    656.660 Range   15677
        Interquartile Range 981.79000
Tests for Location: Mu0=0
Test    Statistic   p Value
Student's t t   225.0917    Pr &gt; |t|    &lt;.0001
Sign    M   9240.5  Pr &gt;= |M|   &lt;.0001
Signed Rank S   85391461    Pr &gt;= |S|   &lt;.0001
Quantiles (Definition 5)
Level   Quantile
100% Max    15680.18
99% 4267.36
95% 2978.88
90% 2475.08
75% Q3  1819.12
50% Median  1258.60
25% Q1  837.33
10% 549.63
5%  415.03
1%  197.90
0% Min  2.85
Extreme Observations
Lowest  Highest
Value   Obs Value   Obs
2.85    3326    10714.3 5837
5.48    6647    10716.4 10470
7.39    6864    12036.4 6658
8.51    17029   12064.8 14329
11.50   16490   15680.2 10454</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="/Users/yipengliu/Desktop/Graduate%20Courses/STATS%20506/Homework/Problem%20Set%204/dollarel_hist.jpg" class="img-fluid figure-img" width="500"></p>
<figcaption class="figure-caption">Histogram of DOLLAREL</figcaption>
</figure>
</div>
</section>
<section id="step-3" class="level3">
<h3 class="anchored" data-anchor-id="step-3">Step 3</h3>
<p>In this part, we generate a histogram of the log of the total electricity cost.</p>
<p>First, we add a column which is the log of DOLLAREL.</p>
<pre class="sas"><code>DATA LOG_WORK;
    SET FILTERED_WORK;
    log_dollarel = LOG(DOLLAREL);
RUN;</code></pre>
<p>Then, we generate the histogram.</p>
<pre class="sas"><code>PROC UNIVARIATE DATA = LOG_WORK;
    VAR log_dollarel;
    HISTOGRAM;
RUN;</code></pre>
<p>Output:</p>
<pre class="sas"><code>The UNIVARIATE Procedure

Variable: log_dollarel

Moments
N   18481   Sum Weights 18481
Mean    7.0882232   Sum Observations    130997.453
Std Deviation   0.62667352  Variance    0.39271971
Skewness    -0.841461   Kurtosis    3.20442521
Uncorrected SS  935796.645  Corrected SS    7257.46015
Coeff Variation 8.84105235  Std Error Mean  0.00460976
Basic Statistical Measures
Location    Variability
Mean    7.088223    Std Deviation   0.62667
Median  7.137755    Variance    0.39272
Mode    6.487166    Range   8.61283
        Interquartile Range 0.77589
Tests for Location: Mu0=0
Test    Statistic   p Value
Student's t t   1537.655    Pr &gt; |t|    &lt;.0001
Sign    M   9240.5  Pr &gt;= |M|   &lt;.0001
Signed Rank S   85391461    Pr &gt;= |S|   &lt;.0001
Quantiles (Definition 5)
Level   Quantile
100% Max    9.66015
99% 8.35875
95% 7.99930
90% 7.81403
75% Q3  7.50611
50% Median  7.13776
25% Q1  6.73022
10% 6.30925
5%  6.02835
1%  5.28776
0% Min  1.04732
Extreme Observations
Lowest  Highest
Value   Obs Value   Obs
1.04732 3326    9.27933 5837
1.70111 6647    9.27953 10470
2.00013 6864    9.39569 6658
2.14124 17029   9.39805 14329
2.44235 16490   9.66015 10454</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="/Users/yipengliu/Desktop/Graduate%20Courses/STATS%20506/Homework/Problem%20Set%204/logdollarel_hist.jpg" class="img-fluid figure-img" width="500"></p>
<figcaption class="figure-caption">Histogram of log_DOLLAREL</figcaption>
</figure>
</div>
</section>
<section id="step-4" class="level3">
<h3 class="anchored" data-anchor-id="step-4">Step 4</h3>
<p>Fit a linear regression model predicting the log of the total electricity cost based upon the number of rooms in the house and whether or not the house has a garage, including the weight variable.</p>
<pre class="sas"><code>PROC REG DATA = WORK.LOG_WORK;
    MODEL log_dollarel = TOTROOMS PRKGPLC1;
    WEIGHT NWEIGHT;
RUN;</code></pre>
<p>Output:</p>
<pre><code>The REG Procedure

Model: MODEL1

Dependent Variable: log_dollarel

Number of Observations Read 18481
Number of Observations Used 18481
Weight: NWEIGHT

Analysis of Variance
Source  DF  Sum of
Squares Mean
Square  F Value Pr &gt; F
Model   2   8899106 4449553 1949.17 &lt;.0001
Error   18478   42181548    2282.79837       
Corrected Total 18480   51080655             
Root MSE    47.77864    R-Square    0.1742
Dependent Mean  7.04925 Adj R-Sq    0.1741
Coeff Var   677.78361        
Parameter Estimates
Variable    DF  Parameter
Estimate    Standard
Error   t Value Pr &gt; |t|
Intercept   1   6.51523 0.01528 426.50  &lt;.0001
TOTROOMS    1   0.08780 0.00226 38.87   &lt;.0001
PRKGPLC1    1   0.06878 0.00416 16.53   &lt;.0001</code></pre>
</section>
<section id="step-5" class="level3">
<h3 class="anchored" data-anchor-id="step-5">Step 5</h3>
<p>Use that model to generate predicted values and create a scatterplot of predicted total electricity cost vs actual total electricity cost.</p>
<pre class="sas"><code>PROC REG DATA = WORK.LOG_WORK;
    MODEL log_dollarel = TOTROOMS PRKGPLC1;
    WEIGHT NWEIGHT;
    OUTPUT OUT = PREDICTION PREDICTED = PREDICTED
RUN;

DATA PREDICTION;
    SET PREDICTION;  
    PREDICTED_VAL = EXP(PREDICTED);
RUN;

PROC SGPLOT DATA = PREDICTION;
    SCATTER x = DOLLAREL y = PREDICTED_VAL;
    XAXIS LABEL="Actual Total Electricity Cost (DOLLAREL)";
    YAXIS LABEL="Predicted Total Electricity Cost (PREDICTED_VAL)";
RUN;</code></pre>
<p>Output:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="/Users/yipengliu/Desktop/Graduate%20Courses/STATS%20506/Homework/Problem%20Set%204/Scatterplot.jpg" class="img-fluid figure-img" width="500"></p>
<figcaption class="figure-caption">Scatter plot of predicted total electricity cost vs actual total electricity cost</figcaption>
</figure>
</div>
</section>
</section>
<section id="problem-4" class="level2">
<h2 class="anchored" data-anchor-id="problem-4">Problem 4</h2>
<section id="part-1.-sas" class="level3">
<h3 class="anchored" data-anchor-id="part-1.-sas">Part 1. SAS</h3>
<p>Import the data into SAS and use proc sql to select only the variables we’ll need for our analysis, as well as subsetting the data if needed. The variables we are goint to use are shown above, according to the Codebook:<br></p>
<p>CaseID: CaseID 2022<br></p>
<p>weight_pop: Post-stratification weight -Main qualified respondents scaled to U.S. population<br></p>
<p>B3: Compared to 12 months ago, would you say that you (and your family) are better off, the same, or worse off financially?<br></p>
<p>ND2: Five years from now, do you think that the chance that you will experience a natural disaster or severe weather event will be higher, lower or about the same as it is now:<br></p>
<p>B7_a: In your community -How would you rate economic conditions today?<br></p>
<p>GH1: This section will ask some questions about your home and your car. Do you (and/or your spouse or partner):<br></p>
<p>ppeducat: Education (4 Categories)<br></p>
<p>race_5cat: Race/Ethnicity -5 categories<br></p>
<pre class="sas"><code>PROC SQL;
   CREATE TABLE public2022_useful AS
   SELECT 
      CaseID,
      weight_pop,
      B3,   
      ND2, 
      B7_a,  
      GH1,
      ppeducat,
      race_5cat
   FROM WORK.IMPORT; 
QUIT;
RUN;</code></pre>
<p>Then, get the data out of SAS and into Stata. We choose to export it as a .csv format.</p>
<pre><code>PROC EXPORT DATA = public2022_useful
    OUTFILE = "~/sasuser.v94/public2022_useful.csv"
    DBMS = CSV REPLACE;
RUN;</code></pre>
</section>
<section id="part-2.-stata" class="level3">
<h3 class="anchored" data-anchor-id="part-2.-stata">Part 2. Stata</h3>
<p>Demonstrate that you’ve successfully extracted the appropriate data by showing the number of observations and variables.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>import delimited <span class="st">"/Users/yipengliu/Desktop/Graduate Courses/STATS 506/Homework/Problem Set 4/public2022_useful.csv"</span>, <span class="kw">clear</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="kw">summarize</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Stata Output:</p>
<pre><code>    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
      caseid |     11,667    5889.991    3397.957          1      11775
  weight_pop |     11,667    21866.31    10952.98   3666.639   88732.65
          b3 |     11,667    2.764035    .9363138          1          5
         nd2 |     11,667    2.633753     .772071          1          5
        b7_a |     11,667    2.225936    .7751958          1          4
-------------+---------------------------------------------------------
         gh1 |     11,667    1.964944    .9790652          1          4
    ppeducat |     11,667    3.071398    .9462462          1          4
   race_5cat |     11,667    1.630925    1.090644          1          5</code></pre>
<p>We proceed to look up the summary of our selected variables in the Codebook:</p>
<pre><code>caseid
Type: Numeric (long)
Range: [1,11775] Units: 1
Unique values: 11,667 Missing .: 0/11,667
Mean: 5889.99
Std. dev.: 3397.96
Percentiles:10%
25%
50%
75%
90%
1178
2949
5890
8829
10601</code></pre>
<pre><code>Type: Numeric (double)
Range: [3666.6386,88732.647] Units: .0001
Unique values: 2,850 Missing .: 0/11,667
Mean: 21866.3
Std. dev.: 10953
Percentiles:
10%
25%
50%
75%
90%
11814.2
15092.1
19790.4
25890
33955.1</code></pre>
<pre><code>b3
Type: Numeric (byte)
Label: B3
Range: [1,5] Units: 1
Unique values: 5 Missing .: 0/11,667
Tabulation:
Freq.
Numeric
Label
1,020
1
Much worse off
3,276
2
Somewhat worse off
5,287
3
About the same
1,605
4
Somewhat better off
479
5
Much better off</code></pre>
<pre><code>nd2
Type: Numeric (byte)
Label: ND2
Range: [1,5] Units: 1
Unique values: 5 Missing .: 0/11,667
Tabulation:
Freq.
Numeric
Label
1,065
1
Much higher
2,915
2
Somewhat higher
7,201
3
About the same
200
4
Somewhat lower
286
5
Much lower</code></pre>
<pre><code>b7_a
Type: Numeric (byte)
Label: B7_A
Range: [1,4] Units: 1
Unique values: 4 Missing .: 0/11,667
Tabulation:
Freq.
Numeric
Label
2,171
1
Poor
5,003
2
Only fair
4,179
3
Good
314
4
Excellent</code></pre>
<pre><code>gh1
Type: Numeric (byte)
Label: GH1
Range: [1,4] Units: 1
Unique values: 4 Missing .: 0/11,667
Tabulation:
Freq.
Numeric
Label
4,982
1
Own your home with a mortgage or loan
2,933
2
Own your home free and clear (without a mortgage or loan)
2,931
3
Pay rent
821
4
Neither own nor pay rent</code></pre>
<pre><code>ppeducat
Type: Numeric (byte)
Label: PPEDUCAT
Range: [1,4] Units: 1
Unique values: 4 Missing .: 0/11,667
Tabulation:
Freq.
Numeric
Label
688
1
No high school diploma or GED
2,772
2
High school graduate (high school diploma or the equivalent GED)
3,226
3
Some college or Associate's degree
4,981
4
Bachelor's degree or higher</code></pre>
<pre><code>race_5cat
Type: Numeric (byte)
Label: race_5cat
Range: [1,5] Units: 1
Unique values: 5 Missing .: 0/11,667
Tabulation:
Freq.
Numeric
Label
8,060
1
White
1,225
2
Black
1,464
3
Hispanic
464
4
Asian
454
5
Other</code></pre>
<p>We can see that the number of rows of the imported data and the number of rows of the data described in the Codebook are consistent, i.e.&nbsp;both of which are 11667. Meanwhile, the basic information of each column of imported data also matches the description of the corresponding column in the Codebook. Therefore, we can assume that the data has been successfully imported.</p>
<p>The response variable is a Likert scale; convert it to a binary of worse off versus same/better. That is, we have to do the following with the column b3: convert 1/2 to 0 (worsed off) and 3/4/5 to 1 (same/better).</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="kw">recode</span> b3 (1=0) (2=0) (3=1) (4=1) (5=1), <span class="kw">generate</span>(b3_binary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Use the following code to tell Stata that the data is from a complex sample:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="kw">svyset</span> caseid [pw = weight_pop]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Stata Output:</p>
<pre><code>Sampling weights: weight_pop
             VCE: linearized
     Single unit: missing
        Strata 1: &lt;one&gt;
 Sampling unit 1: caseid
           FPC 1: &lt;zero&gt;</code></pre>
<p>Carry out a logisitic regression model accounting for the complex survey design. In this case, we treat all of the predictors as categorical:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="kw">svy</span>: <span class="kw">logit</span> b3_binary i.nd2 i.b7_a i.gh1 i.ppeducat i.race_5cat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Stata Output:</p>
<pre><code>(running logit on estimation sample)

Survey: Logistic regression

Number of strata =      1                        Number of obs   =      11,667
Number of PSUs   = 11,667                        Population size = 255,114,223
                                                 Design df       =      11,666
                                                 F(17, 11650)    =       55.16
                                                 Prob &gt; F        =      0.0000

------------------------------------------------------------------------------
             |             Linearized
   b3_binary | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         nd2 |
          2  |   .0516539   .0920761     0.56   0.575    -.1288307    .2321385
          3  |  -.0168983    .085543    -0.20   0.843    -.1845769    .1507802
          4  |   .2395472   .1992676     1.20   0.229    -.1510506     .630145
          5  |   .2256698    .167205     1.35   0.177      -.10208    .5534197
             |
        b7_a |
          2  |    .812257   .0600331    13.53   0.000     .6945821    .9299318
          3  |    1.76666    .067935    26.01   0.000     1.633496    1.899824
          4  |   2.605681   .1981719    13.15   0.000     2.217231    2.994131
             |
         gh1 |
          2  |  -.0302041   .0563929    -0.54   0.592    -.1407436    .0803354
          3  |   .1143763   .0589749     1.94   0.052    -.0012243    .2299769
          4  |   .3674756   .0977701     3.76   0.000     .1758299    .5591214
             |
    ppeducat |
          2  |  -.0198248   .1019437    -0.19   0.846    -.2196516    .1800019
          3  |   .0132185   .0988547     0.13   0.894    -.1805532    .2069902
          4  |   .0737979   .0984407     0.75   0.453    -.1191623    .2667581
             |
   race_5cat |
          2  |   .8555888   .0808241    10.59   0.000       .69716    1.014017
          3  |   .2646536   .0706892     3.74   0.000     .1260909    .4032164
          4  |   .5486136   .1243165     4.41   0.000     .3049326    .7922947
          5  |   .0077989   .1677612     0.05   0.963    -.3210411    .3366389
             |
       _cons |   -.603436   .1319128    -4.57   0.000    -.8620071   -.3448648
------------------------------------------------------------------------------</code></pre>
<p>The researchers question of interest is whether the respondent’s family is better off, the same, or worse off financially compared to 12 month’s ago can be predicted by thinking that the chance of experiencing a natural disaster or severe weather event will be higher, lower or about the same in 5 years. From the output above, we can conclude that when the respondents’ assessment of the economic conditions today in the country, their housing situation, their level of education and their race are fixed, Each of the dummy variables generated by the categorical predictor “the chance of experiencing a natural disaster or severe weather event will be higher, lower or about the same in 5 years” is not significant (they all have large p-values). Therefore, the question of interest to the researchers cannot be answered by our output of the logistic regression for now.</p>
<p>Finally, we get the data out of Stata and into R.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>cd <span class="st">"/Users/yipengliu/Desktop/Graduate Courses/STATS 506/Homework/Problem Set 4"</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="kw">export</span> delimited <span class="kw">using</span> <span class="st">"public2022_useful_edited.csv"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Stata Output:</p>
<pre><code>file public2022_useful_edited.csv saved</code></pre>
</section>
<section id="part-3.-r" class="level3">
<h3 class="anchored" data-anchor-id="part-3.-r">Part 3. R</h3>
<p>First, we load the .csv file into R and check the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>public2022 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"/Users/yipengliu/Desktop/Graduate Courses/STATS 506/Homework/Problem Set 4/public2022_useful_edited.csv"</span>, </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(public2022, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  caseid weight_pop b3 nd2 b7_a gh1 ppeducat race_5cat b3_binary
1      1   12033.68  5   2    2   3        4         1         1
2      2   21579.21  3   3    2   2        4         1         1
3      3   20043.89  3   3    2   3        3         3         1
4      4   21793.37  2   3    1   3        4         1         0
5      5   13900.41  2   1    3   1        4         1         0</code></pre>
</div>
</div>
<p>Use the survey package to obtain the pseudo <span class="math inline">\(R^2\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a complex survey design object</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: grid</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'survey'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:graphics':

    dotchart</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>my_svydesign <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span> caseid, <span class="at">weight =</span> <span class="sc">~</span> weight_pop, <span class="at">data =</span> public2022)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Treat predictors as categorical variables</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>public2022<span class="sc">$</span>nd2 <span class="ot">&lt;-</span> <span class="fu">factor</span>(public2022<span class="sc">$</span>nd2)</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>public2022<span class="sc">$</span>b7_a <span class="ot">&lt;-</span> <span class="fu">factor</span>(public2022<span class="sc">$</span>b7_a)</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>public2022<span class="sc">$</span>gh1 <span class="ot">&lt;-</span> <span class="fu">factor</span>(public2022<span class="sc">$</span>gh1)</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>public2022<span class="sc">$</span>ppeducat <span class="ot">&lt;-</span> <span class="fu">factor</span>(public2022<span class="sc">$</span>ppeducat)</span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>public2022<span class="sc">$</span>race_5cat <span class="ot">&lt;-</span> <span class="fu">factor</span>(public2022<span class="sc">$</span>race_5cat)</span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the logistic regression model</span></span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a>my_glm <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(b3_binary<span class="sc">~</span>nd2<span class="sc">+</span>b7_a<span class="sc">+</span>gh1<span class="sc">+</span>ppeducat<span class="sc">+</span>race_5cat, </span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">design =</span> my_svydesign)</span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain the pseudo R2</span></span>
<span id="cb88-15"><a href="#cb88-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsq)</span>
<span id="cb88-16"><a href="#cb88-16" aria-hidden="true" tabindex="-1"></a>pseudo_r2 <span class="ot">&lt;-</span> <span class="fu">rsq</span>(my_glm)</span>
<span id="cb88-17"><a href="#cb88-17" aria-hidden="true" tabindex="-1"></a>pseudo_r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09526968</code></pre>
</div>
</div>
<p>It can be seen that the pseudo <span class="math inline">\(R^2\)</span> of this model is 0.09526968.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>